export const theme = {
  colors: {
    primary: '#6366f1',
    secondary: '#0d0d1a',
    background: '#0a0a0f',
    surface: '#16161d',
    text: {
      primary: '#e5e5e5',
      secondary: '#9ca3af',
    },
    border: '#2a2a35',
    white: '#ffffff',
    error: '#ef4444',
    success: '#22c55e',
    accent: {
      light: '#a5b4fc',
      muted: '#c7c9d1',
    },
    glow: 'rgba(99, 102, 241, 0.3)',
    glowBorder: 'rgba(99, 102, 241, 0.4)',
    glowCard: 'rgba(99, 102, 241, 0.1)',
    glowHover: 'rgba(99, 102, 241, 0.08)',
    star: '#f59e0b',
    gradient: {
      heroStart: '#0d0d1a',
      heroMid: '#1e1b4b',
      sectionDark: '#0d0d1f',
    },
  },
  fonts: {
    sans: [
      '-apple-system',
      'BlinkMacSystemFont',
      '"Segoe UI"',
      'Roboto',
      '"Helvetica Neue"',
      'Arial',
      'sans-serif',
    ].join(', '),
    mono: [
      'ui-monospace',
      'SFMono-Regular',
      'Menlo',
      'Monaco',
      'Consolas',
      '"Liberation Mono"',
      '"Courier New"',
      'monospace',
    ].join(', '),
  },
  fontSizes: {
    xs: '0.75rem',
    sm: '0.875rem',
    md: '1rem',
    lg: '1.125rem',
    xl: '1.25rem',
    '2xl': '1.5rem',
    '3xl': '1.875rem',
    '4xl': '2.25rem',
    '5xl': '3rem',
  },
  spacing: {
    xs: '0.25rem',
    sm: '0.5rem',
    md: '1rem',
    lg: '1.5rem',
    xl: '2rem',
    '2xl': '3rem',
    '3xl': '4rem',
  },
  borderRadius: {
    sm: '0.25rem',
    md: '0.375rem',
    lg: '0.5rem',
    xl: '0.75rem',
    full: '9999px',
  },
  breakpoints: {
    sm: '640px',
    md: '768px',
    lg: '1024px',
    xl: '1280px',
  },
} as const;

export type Theme = typeof theme;
